### PR TITLE
Updated the desktop file, because in my case ~/.local bin wasn't in t…

### PR DESCRIPTION
**Pull request by alx365**
…he path

title. It should make the installation and first run experience easier, since you don't have to debug and find out, why the executable wasn't found.

### CODE REVIEW

**Comment by lawl** [comment]
Makes sense.

**Comment by alx365** [comment]
Thanks!

**Comment by lawl** [comment]
This broke the desktop file for me and gnome didn't show the icon anymore. Had to revert. I was already shipping this, oops, I need to be more careful.

Need to find a better solution for this.

**Comment by alx365** [comment]
Ok. that sucks, it definitely helped me. (KDE Plasma, arch linux)

**Pull request merged**
