### PR TITLE
Delete vendor folder - Go mod allows developers to keep dependencies local

### PR DESCRIPTION
**Pull request by Dadadah**
During this audit, it would be helpful to remove unnecessary code from this repository. Currently, the project is storing it's dependencies in git; however, since it's using Go mod this is not necessary.

It's common practice to keep the vendor folder in the `.gitignore` file to keep repository size down. You can repopulate the vendor folder locally by running `go mod vendor`.

@lawl you mentioned that the most likely area for unauthorized code would be in the large commits containing dependencies. This change should eliminate that possibility.

### CODE REVIEW

**Comment by lawl** [comment]
if you can repopulate it the exact same way, why does it matter to you? self contradictory.

**Comment by Foxite** [comment]
When cloning this repository you wouldn't need to download the entire history of all your dependencies, and Go's tools could just download the latest versions which is much less data. This saves time, especially on slower connections, and not everyone has unlimited data on their internet connections.

Also, although this isn't going to help you *now*, if you had done this from the start, you wouldn't need to audit every single line in every single update of every single one of your dependencies. It's just good practice and there is no reason not to do it.

**Comment by luni3359** [comment]
I'm kind of shocked that the dependencies were in the repo. They shouldn't be committed anyway.

**Comment by lawl** [comment]
that depends entirely on what you want to achieve. i don't feel like debating the pros and cons of pushing the vendor folder right now.

**Comment by exikyut** [comment]
If I understand correctly, removing the dependencies would a) bring the total "needs audit" size down and b) shift responsibility for securely updating those dependencies to the Go mod ecosystem, in perpetuity.

> if you can repopulate it the exact same way, why does it matter to you? self contradictory.

If it repopulates the exact same way, well, I'd lean toward taking that as a fairly positive signal that the dependencies are probably alright.

> i don't feel like debating the pros and cons of pushing the vendor folder right now.

Well, the internet hates information vacuums, but thanks for clarifying that there is extra context we're missing. We look forward to hearing more once you're back on your feet!

**Pull request closed without merging**
